### ISSUE TITLE
Protokol, level loading

### ISSUE THREAD

**Issue by KolouchPetr** [parni-mlaticky/ICP#22]
Level loading by měl načítat ze stringu ne ze souboru = optimálnější, prvně se po síti pošle grid

**Comment by OndrejZobal** [comment]
# Protokol záznamu

```
<grid-size-x> <grid-size-y>
<grid>
D <id> <direction>
Y <id>
< . . . >
T
D <id> <direction>
T 
```

## Význam značek

- `grid-size-x`: Velikost bludiště na ose X
- `grid-size-y`: Velikost bludiště na ose Y
- `grid`: Grid jako ve vstupním souboru
- `D`: Změna směru entity `id` na `direction`
- `Y`: (you) Informace o tom, kterého hráče ovládá vzdálený hráč (pouze MP, replay tohle může ignorovat)
- `T`: začátek dalšího logického ticku.

## Význam atributů

- `id`: desítkové celé kladné číslo, jedinečně identifikuje entitu. čísla id se budou přidělovat všem entitám v pořadí ve kterém se budou vytvářet počínaje číslem 0.
- `direction`: směr ve formátu `x,y`, kde hodnoty směru odpovídají směru momentálně ve hře, tedy jedna z proměnných bude 0 a druhá bude buď -1, 1 nebo 0.

## Popis

Grid se bude posílat ve stejném formátu jako je v souboru, tím si ušetříme psaní další funkce pro načnítání levelu (to nám ušetří psaní dalšího level parseru a navíc zaručí že čísla `id` budou pokaždé stejná). V současné době loadlevel čte soubor, což ale není vyhovující, kvůli výkonu. Level::loadLevel by měl získat grid skrz string, který může procházet třeba pomocí iterátoru. V případě SP by se obash levelu načetl jedním voláním read v mainwindow, v případě slave MP by ten string dostal po síti.

Veškeré další věci se dají vyčíst ze změny směru, takže si je dopočítá level. To platí i pro případnž změny v UI jak je například sebrání klíče, ztracení života atd.

Prvně implementujeme:
 - Nahrávání savefilů
 - Přehrávání savefilů
 - pak až MP.
 
 Lokální přehrávání se bude jednodušejí testovat imho, takže server-side protokol můžeme vypilovat na tom, dále pokud to nebude fungovat, tak aspoň budeme vědět, že to není kvůli latenci.
 
# Návrh S -> M komunikace při MP

```
D <id> <direction>
```

Význam by byl stejný jako u M -> S komunikaci, ale slave by mohl hýbat pouze s id vlastního hráče (které master označil Y). Myslím si že další synchronizace není potřeba (clueless). Co se týče navázání spojení a jeho uknočení, to za nás vyřeší TCP.

V případě klienta se tahle změna bude posílat častěji než jednou za tick. Server tyhle změny bude sbírat a zanášet do player entity. A při pudatování gridu se použije poslední změna, která se do playera nastavila.

* * *
*Btw. počítám s tím, že MP bude nejvýš mezi 2ma lidma, doufám, že nejsem úplně clueless xdd.*

@hucovic-vladimir @KolouchPetr RFC :blush:

**Comment by KolouchPetr** [comment]
Za mě v pohodě

**Comment by OndrejZobal** [comment]
za mě taky.

**Comment by OndrejZobal** [comment]
V zásadě Ačkový projekt.

**Comment by hucovic-vladimir** [comment]
💪 💪 💪 💪 💪
